version: "3.8"

services:
  mysql:
    image: mysql:8.0
    platform: linux/arm64
    container_name: mysql-cms-jayalaksana
    restart: always
    environment:
      MYSQL_DATABASE: cms_jayalaksana
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  dbdata: